import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

/**
 * Prepares the isolated test database and generates .env.test
 *
 *  1. Derives a DATABASE_URL scoped to the `churcheden_test` schema (never touches dev data)
 *  2. Ensures the schema exists
 *  3. Pushes the Prisma schema fresh (`prisma db push --schema ... --accept-data-loss --force-reset`)
 *  4. Writes .env.test with dummy/non-secret provider keys (emails, payments,
 *     storage and Google OAuth are all mocked by the test suite)
 */
const ROOT = process.cwd();
const TEST_SCHEMA = process.env.TEST_DB_SCHEMA ?? 'churcheden_test';
const ENV_TEST_PATH = join(ROOT, '.env.test');
const PRISMA_CLI = join(ROOT, 'node_modules', 'prisma', 'build', 'index.js');

const parseDotEnv = (filePath: string): Record<string, string> => {
    if (!existsSync(filePath)) return {};
    const vars: Record<string, string> = {};
    for (const line of readFileSync(filePath, 'utf8').split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq <= 0) continue;
        const key = trimmed.slice(0, eq).trim();
        let value = trimmed.slice(eq + 1).trim();
        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }
        vars[key] = value;
    }
    return vars;
};

const resolveBaseUrl = (): string => {
    if (process.env.DATABASE_URL) return process.env.DATABASE_URL;
    const vars = parseDotEnv(join(ROOT, '.env'));
    const url = vars.DATABASE_URL;
    if (!url) {
        throw new Error('DATABASE_URL is required. Set it in the environment or in .env');
    }
    return url;
};

const withSchema = (baseUrl: string, schema: string): string => {
    const separator = baseUrl.includes('?') ? '&' : '?';
    return `${baseUrl}${separator}schema=${schema}`;
};

const runPrisma = (
    args: string[],
    envOverrides: Record<string, string>,
    stdin?: string,
): void => {
    const result = spawnSync(process.execPath, [PRISMA_CLI, ...args], {
        cwd: ROOT,
        env: { ...process.env, ...envOverrides } as NodeJS.ProcessEnv,
        encoding: 'utf8',
        input: stdin,
        shell: false,
        maxBuffer: 10 * 1024 * 1024,
    });

    if (result.stdout?.trim()) console.log(result.stdout.trim());
    if (result.stderr?.trim()) console.error(result.stderr.trim());
    if (result.status !== 0) {
        throw new Error(`prisma ${args.join(' ')} failed with exit code ${result.status}`);
    }
};

const baseUrl = resolveBaseUrl();
const testUrl = withSchema(baseUrl, TEST_SCHEMA);

console.log(`Using test database: ${testUrl.split('@').pop() ?? testUrl}`);

console.log(`Ensuring schema "${TEST_SCHEMA}" exists...`);
runPrisma(
    ['db', 'execute', '--stdin'],
    { DATABASE_URL: baseUrl },
    `CREATE SCHEMA IF NOT EXISTS "${TEST_SCHEMA}";`,
);

console.log('Pushing Prisma schema to the test database...');
runPrisma(
    [
        'db',
        'push',
        '--schema=prisma/schema.prisma',
        '--accept-data-loss',
        '--force-reset',
    ],
    { DATABASE_URL: testUrl },
);

const envTest = [
    '# Auto-generated by scripts/test-db-setup.ts - do not edit.',
    '# Provider keys below are placeholders: emails, payments, storage and Google are mocked in tests.',
    'NODE_ENV=testing',
    `DATABASE_URL=${testUrl}`,
    'PORT=8080',
    'BCRYPT_ROUNDS=10',
    'REDIS_URL=redis://localhost:6379',
    'REDIS_TCP_URL=redis://localhost:6379',
    'RESEND_API_KEY=re_test_dummy_key',
    'EMAIL_FROM=no-reply@churcheden.app',
    'FRONTEND_URL=https://churcheden.app',
    'ACCESS_TOKEN_SECRET=test-access-secret-0123456789abcdef0123456789abcdef',
    'REFRESH_TOKEN_SECRET=test-refresh-secret-0123456789abcdef0123456789abcdef',
    'ACCESS_TOKEN_EXPIRES_IN=15m',
    'REFRESH_TOKEN_EXPIRES_IN=7d',
    'GOOGLE_CLIENT_ID=test-client-id',
    'GOOGLE_CLIENT_SECRET=test-client-secret',
    'GOOGLE_CALLBACK_URL=http://localhost:8080/api/v1/auth/google/callback',
    'CLOUDFLARE_R2_ACCESS_KEY_ID=test-access-key',
    'CLOUDFLARE_R2_SECRET_ACCESS_KEY=test-secret-key',
    'CLOUDFLARE_R2_ENDPOINT=https://test.r2.cloudflarestorage.com',
    'CLOUDFLARE_R2_BUCKET_NAME=churcheden-test',
    'CLOUDFLARE_R2_PUBLIC_URL=https://cdn.test.churcheden.app',
    'PAYSTACK_SECRET_KEY=sk_test_dummy',
    'PAYSTACK_PLAN_CODE=PLN_test_plan',
    'SUBSCRIPTION_AMOUNT_KOBO=20000',
    '',
].join('\n');

writeFileSync(ENV_TEST_PATH, envTest, 'utf8');
console.log(`Wrote ${ENV_TEST_PATH}`);